export type SpecFileType = 'design' | 'agents' | 'manifest'

/**
 * Generates a DESIGN.md following the Google Stitch DESIGN.md format.
 * The format uses H1 for the app name, H2 for screen names, and prose
 * descriptions that AI design tools can parse into visual mockups.
 */
export function generateDesignMd(projectName: string, description?: string): string {
  const today = new Date().toISOString().slice(0, 10)
  return `# ${projectName}

${description ?? `${projectName} is a modern web application designed to help users accomplish their goals efficiently.`}

## Home

The main landing screen welcoming users to ${projectName}. Features a clean hero section with the app's value proposition prominently displayed, a primary call-to-action button, and a brief overview of key features arranged in a grid below. The navigation bar at the top contains the logo, links to main sections, and a sign-in button. The background is light with subtle texture.

## Dashboard

The primary workspace shown after the user signs in. The header displays the user's name and avatar alongside a notification bell. The left sidebar contains navigation links grouped by category. The main content area shows a summary of recent activity, key metrics displayed as stat cards, and a list of recent items. A floating action button in the bottom right corner opens a quick-create dialog.

## Detail View

A focused view showing the full details of a single item. The page header includes a back button, the item title, and action buttons for editing and sharing. The main content is divided into a primary column with the full content and a narrower sidebar showing metadata, related items, and status information. A sticky bottom bar on mobile shows the primary actions.

## Settings

User account and application preferences. Organized into a tabbed layout with sections for Profile, Notifications, Security, and Appearance. Each section contains labeled form fields, toggles, and selectors. Changes are saved automatically with a subtle confirmation toast. The page uses a two-column layout on desktop with a navigation list on the left and content on the right.

## Onboarding

A multi-step welcome flow for new users. Each step takes up the full viewport with a centered card. Step indicators at the top show progress. Each step has a clear heading, concise description, and a single focused input or choice. Navigation buttons sit at the bottom of the card. The final step shows a celebration animation and a "Get Started" button.

---

<!-- Generated by Forge on ${today} -->
<!-- Format: https://stitch.withgoogle.com/docs/design-md/format -->
`
}

/**
 * Generates an AGENTS.md file with instructions for AI agents working on the project.
 */
export function generateAgentsMd(projectName: string, description?: string): string {
  return `# AGENTS.md — ${projectName}

## Project Overview

${description ?? `${projectName} is a web application. This file contains instructions for AI agents working on this codebase.`}

## Architecture

- **Frontend**: React + TypeScript + Tailwind CSS
- **Routing**: React Router
- **Build**: Vite
- **State**: React context + hooks (no global state library)

## File Structure

\`\`\`
src/
  components/    # React UI components (PascalCase filenames)
  lib/           # Utilities, hooks, loaders (camelCase)
  types/         # TypeScript type definitions
  assets/        # Images and static resources
public/          # Static files served as-is
\`\`\`

## Development Guidelines

### Code Style
- TypeScript for all new files; no \`any\` unless unavoidable
- Functional components with hooks only — no class components
- Tailwind CSS for all styling; no inline styles or CSS modules
- Keep components small and single-purpose

### Naming Conventions
- Components: \`PascalCase\` (e.g., \`UserProfile.tsx\`)
- Hooks: \`camelCase\` with \`use\` prefix (e.g., \`useProjectData.ts\`)
- Types/interfaces: \`PascalCase\` (e.g., \`UserData\`)
- Constants: \`UPPER_SNAKE_CASE\`

### Component Patterns
\`\`\`tsx
// Preferred component pattern
interface Props {
  value: string
  onChange: (value: string) => void
}

export function MyComponent({ value, onChange }: Props) {
  return <div>{value}</div>
}
\`\`\`

### Testing New Features
1. Run \`npm run dev\` and test in browser
2. Check both light and dark themes
3. Test on mobile viewport (375px wide)
4. Run \`npm run build\` to verify no TypeScript errors

## Key Conventions

- No default exports for components (use named exports)
- Co-locate types with the component/module that uses them; only shared types go in \`src/types/\`
- Prefer composition over prop-drilling; use React context for shared state that spans many components
- All user-facing strings should be easily replaceable (no deeply embedded text)

## Do Not

- Add new dependencies without considering bundle size impact
- Bypass TypeScript with \`// @ts-ignore\` without a comment explaining why
- Write comments that describe *what* code does (the code itself should be clear); only comment *why* when non-obvious
`
}

/**
 * Generates a MANIFEST.md with project metadata and tech stack overview.
 */
export function generateManifestMd(projectName: string, description?: string): string {
  const today = new Date().toISOString().slice(0, 10)
  return `# MANIFEST.md — ${projectName}

**Created**: ${today}
**Status**: Active

## Description

${description ?? projectName}

## Tech Stack

| Layer       | Technology         | Version |
|-------------|--------------------|---------|
| Framework   | React              | 19.x    |
| Language    | TypeScript         | 5.x     |
| Styling     | Tailwind CSS       | 4.x     |
| Build tool  | Vite               | 7.x     |
| Routing     | React Router       | 7.x     |
| Icons       | Lucide React       | latest  |

## Project Structure

\`\`\`
/
├── src/
│   ├── components/    # UI components
│   │   └── ui/        # Base UI primitives (Radix-based)
│   ├── lib/           # Utilities, hooks, data loaders
│   ├── types/         # Shared TypeScript types
│   └── assets/        # Images and static resources
├── public/            # Static files
├── package.json
├── vite.config.ts
└── tsconfig.json
\`\`\`

## Key Features

- [ ] Feature 1
- [ ] Feature 2
- [ ] Feature 3

## Design Decisions

| Decision | Choice | Reason |
|----------|--------|--------|
| Styling | Tailwind CSS | Utility-first, consistent design tokens |
| State | React context | Sufficient for app complexity; avoids extra dependency |
| Build | Vite | Fast HMR, excellent TypeScript support |

## Environment Variables

| Variable | Description | Required |
|----------|-------------|----------|
| \`VITE_API_URL\` | Backend API base URL | No |

## Scripts

\`\`\`bash
npm run dev       # Start development server
npm run build     # Production build
npm run preview   # Preview production build
npm run lint      # Run ESLint
\`\`\`

## Spec Files

| File | Purpose |
|------|---------|
| \`DESIGN.md\` | UI screen specifications (Stitch format) |
| \`AGENTS.md\` | AI agent instructions and conventions |
| \`MANIFEST.md\` | This file — project metadata |
`
}

export const SPEC_FILE_META: Record<SpecFileType, {
  filename: string
  label: string
  description: string
  badge: string
}> = {
  design: {
    filename: 'DESIGN.md',
    label: 'DESIGN.md',
    description: 'UI screen specifications in Google Stitch DESIGN.md format. Describes each screen with prose that AI design tools can parse into visual mockups.',
    badge: 'Stitch format',
  },
  agents: {
    filename: 'AGENTS.md',
    label: 'AGENTS.md',
    description: 'Instructions and conventions for AI agents (Claude, Copilot, etc.) working on this project. Covers architecture, file structure, and coding guidelines.',
    badge: 'AI guidance',
  },
  manifest: {
    filename: 'MANIFEST.md',
    label: 'MANIFEST.md',
    description: 'Project manifest with tech stack, file structure, key decisions, and environment variables. A single source of truth for project metadata.',
    badge: 'Metadata',
  },
}
